### ISSUE TITLE
Review/Feedback form 

### ISSUE THREAD

**Issue by Mystik01** [kyb3r/modmail#2807]
**Is your feature request related to a problem? Please describe.**

I'm not frustrated.

**Describe the solution you'd like**

When a mod closes a ticket it should send a reply back to the user saying something like "how did @staff-member do". It should ask how much out of 10 would you rate @staff-members. And if the number is less that 10 is should say, what can we improve on? Etc

**Describe alternatives you've considered**
The bot replying at the with just a Google form link.

**Who will this benefit**
Does this feature apply to a great portion of users?

Benefits everyone, mods know what they need to work on next time and the users will then be more happy next time they use support.
**Additional context**

Optional feature, so can be disabled if owners don't want it.

**Comment by StephenDaDev** [comment]
Hello! While in theory, this idea is brilliant, in execution it turns out to not be as good as you would hope. I personally used to run a survey program __very__ similar to what you are suggesting in the Modmail Support server. As I said before, in theory, it was great, but it really wasn't. It annoyed the people receiving support to be getting additional DMs, most flat out ignored it, and then complained about it being a pain every time later on. Most people said 10, and "Thanks" and that was about it, there were times where you could tell the user was frustrated with the supporter and still said 10, sometimes saying 10 and then complaining about them in other chats. While I can see why it wanted, and I can belive in some servers it would work, I simply don't think it would work for most servers/most users.

**Comment by RealCyGuy** [comment]
One way this could happen could be, in the close message, it says "react with 🗳️ to leave a review". Then, when a user reacts, they get an interactive survey because they wanted to. No extra dm's, no forced reviews.

**Comment by misa-coder** [comment]
Adding config option to enable/disable it in some server is also a gr8 idea. Most of the team staff team closed the ticket without answering it and delete the log message too. I removed logs delete perms from them but still. They can delete the embed msg. Adding a web dashboard which always shows all the logs for the server and other details will be gr8 but I think this is a gr8 addition

**Comment by lorenzo132** [comment]
Hey misa, you always can do: `?logs @user` to retrieve the complete logs of a specific person. which means u can see the person its thread online at your logviewer site. All this without any deleted messages or deleted embeds

**Comment by Mystik-Rogue** [comment]
> One way this could happen could be, in the close message, it says "react with 🗳️ to leave a review". Then, when a user reacts, they get an interactive survey because they wanted to. No extra dm's, no forced reviews.

@RealCyGuy That would be an even better idea!

should i keep this suggestion open or shall i close it?

**Comment by ririko5834** [comment]
👍 From me


> One way this could happen could be, in the close message, it says "react with 🗳️ to leave a review". Then, when a user reacts, they get an interactive survey because they wanted to. No extra dm's, no forced reviews.

**Comment by fourjr** [comment]
This is not in the scope of Modmail and should be done as a plugin
