### ISSUE TITLE
Deleting a image in a thread from dm shows as not working while it deletes

### ISSUE THREAD

**Issue by lorenzo132** [kyb3r/modmail#2910]
**Describe the bug**
When you send a image to the contacted user from a thread and delete the image from the thread it will say "failed to delete message" while it got deleted sucesfully.

**Bot Info**
Bot version (check with `@modmail about`): 3.7.14.dev1
Host method (Heroku, self-host, etc): selfhost

**To Reproduce**
1. Who can reproduce (ex. anyone, owners)? those that have access to threads.
2. Where can it be reproduced (ex. in thread channels, recipient DM's)? Thread channels
3. Done what to cause the error? Send a image in a thread, delete the image > it will show as not deleted while it got deleted
4. Any recently made changes to your bot? No recent changes
5. Errored as said

**Error Logs**
If your Modmail bot is online, type `@modmail debug hastebin` and include the link here: https://hasteb.in/ediguhon
If your Modmail bot is not online or the previous command did not generate a link, do the following:

1. Select your *bot* application at https://dashboard.heroku.com
2. [Restart your bot](https://i.imgur.com/3FcrlKz.png)
3. Reproduce the error to populate the error logs
4. [Copy and paste the logs](https://i.imgur.com/TTrhitm.png)

**Screenshots**
Add screenshots to help explain your problem. [VIDEO] https://cdn.discordapp.com/attachments/670004205435486228/784849870967013406/SPOILER_Desktop_2020.12.05_-_19.26.08.01.mp4                                                                     ←↑
                                                                                                    ↑  
**Additional context**                                                                 |
Add any other context about the problem here.                        |
-- No other context --                                                                 |
                                                                                                    |
issue is shown step by step in the video linked       - - - - - - - --

**Comment by fourjr** [comment]
I managed to reproduce this on the test bot but can't reproduce locally.

**Comment by wolfier74** [comment]
Same problem

**Comment by DeltoidDelta** [comment]
Hi there,

Thank you for reporting the bug! I ran into similar issue, even with just plain text messages. When I attempt to delete a message on a thread, it actually deletes the message for recipient, but falsely reports that, "Failed to delete message."

Please let me know if you would like more details on this matter, I would be happy to provide them!

**Comment by Jerrie-Aries** [comment]
Hello, I tested this, and I think I found a solution for it.
I think it doesn't related to image at all, because deleting a normal thread message (using command) would throw the same error (at least when I tested it).

It's because the `delete_message` function in `thread.py` has been called twice:
1. From the `delete` command in `modmail.py`. (This deletes both messages in thread and DM)
2. From `on_message_delete` in `bot.py`. (This was triggered because a message in thread channel was deleted, and it finds the linked message in DM, which has already been deleted by the 1# call). This causes the error.

Solution is (what I tried), don't let the bot delete the message in the DM from the 1# call and let it automatically delete it on the 2# call (which is triggered when a message in thread channel is deleted).


Original code in `thread.py`:
```py
    async def delete_message(
        self, message: typing.Union[int, discord.Message] = None, note: bool = True
    ) -> None:
        if isinstance(message, discord.Message):
            message1, message2 = await self.find_linked_messages(message1=message, note=note)
        else:
            message1, message2 = await self.find_linked_messages(message, note=note)
        tasks = []
        if not isinstance(message, discord.Message):
            tasks += [message1.delete()]
        if message2 is not None:
            tasks += [message2.delete()]
        elif message1.embeds[0].author.name.startswith("Persistent Note"):
            tasks += [self.bot.api.delete_note(message1.id)]
        if tasks:
            await asyncio.gather(*tasks)
```

**Change the:**
```py
if message2 is not None:
```

**to:**
```py
elif message2 is not None:
```
This is what I figured.
Maybe you guys can check that out?

**Comment by fourjr** [comment]
@Jerrie-Aries, thanks for the contribution! I managed to reproduce and use your solution and it worked. In the future, it'd be great if you can properly contribute to modmail via PRs! :)
