### ISSUE TITLE
[BUG] Contacting yourself will trigger the mention. 

### ISSUE THREAD

**Issue by Akarys42** [kyb3r/modmail#2929]
**Describe the bug**
If you run `?selfcontact` or even manually `?contact` yourself, it will trigger the mention due to the fact that the creator and the recipient is the same person. The faulty code seems to be this if
https://github.com/kyb3r/modmail/blob/35f24eec0eddeb42ab785014de1efd9298ed89df/core/thread.py#L158

**Bot Info**
Bot version (check with `@modmail about`): 3.80
Host method (Heroku, self-host, etc): Self-hosted

**To Reproduce**
1. Who can reproduce (ex. anyone, owners)? Anyone
2. Where can it be reproduced (ex. in thread channels, recipient DM's)? Anywhere
3. Done what to cause the error? Running the command `?selfcontact` or `?contact` with your own ID
4. Any recently made changes to your bot? The `mention` configuration entry has to be set.

**Comment by Jerrie-Aries** [comment]
I was confused as well when I read this issue at first. Then I checked the code on the older version, the output is still the same. 
I think the code ain't wrong.

Try to look it this way:
-The `selfcontact` command is meant for the user to contact Staff via command, even tho it invokes the `contact` command but still it's equal to them DM'ing Modmail directly, that's why it triggers the mention, so in this case `creator == recipient`.

-Meanwhile the `contact` command is for the Staff to contact the user, this doesn't need to trigger the mention because one of the Staff (the one that uses the command) is fully aware the thread is being created. In this case, `creator != recipient`. So `mention = None`.

You triggered the mention because you were using those commands to contact yourself (`creator == recipient`).

I'm sorry if I'm wrong about this. 😅

**Comment by StephenDaDev** [comment]
I'm going to agree that this most likely is a side-effect of an intended feature as stated by the reply above me. There is the benefit of being able to silently contact yourself, however, is it worth the effort of fixing this or not is really the question.

**Comment by fourjr** [comment]
Thanks for the explanation @Jerrie-Aries, that basically sums up why it pings.

There are no plans to "fix" this as it does not have any "real world impact". How many times will a mod create a thread with themselves for testing?
