### ISSUE TITLE
Anonymous Reply Highest role 

### ISSUE THREAD

**Issue by matrix2113** [kyb3r/modmail#3014]
**Describe the solution you'd like**
Update [this](https://github.com/kyb3r/modmail/blob/master/core/thread.py#L865) from `author.top_role` to be the highest hoisted role. 

**Who will this benefit**
Helps user so it doesn't show `^` or `*` to be the highest role in the embed. It'll show the next role under if it's hoisted like Admin or something.

**Comment by StephenDaDev** [comment]
This would be beneficial to many users. A very large chunk of servers use roles like these or similar to give higher-level admin privileges, which often causes an issue. Another thing I have talked to people who want to do something where it just shows "Moderation Team" "Partnership Manager" etc instead of the actual rank of the staff member (but not the same for everyone).

**Comment by onerandomusername** [comment]
Perhaps rather than editing that, adding a configuration for blacklisting roles from the highest role?

Or maybe a combination of both.

**Comment by StephenDaDev** [comment]
It'd probably be easier for everyone involved to just use the highest hoisted.

**Comment by fourjr** [comment]
Added in 3.10.0-dev5
