### ISSUE TITLE
[BUG] Everyone gaining owner perms, without being granted them

### ISSUE THREAD

**Issue by coleslaw12** [kyb3r/modmail#3016]
**Describe the bug**
So at some point my bot gave @everyone owner perms, and to no avail using the ?perms remove level 5 <everyone/all>, neglected to remove the perms. The only possible way was by going through the config file in MongoDB and removing it manually and restarting the bot. 

**Bot Info**
Bot version (check with `@modmail about`): 3.9.2
Host method (Heroku, self-host, etc): Heroku with MongoDB

**To Reproduce**
I'm not exactly sure what caused the error but was hoping that it could be made so that, everyone cant gain owner perms without editing it in a config file. This way the bot doesn't have the ability to grant those permissions to everyone, as again i have 0 clue how this happened. 

Aside, when doing ?perms get everyone, it neglects to show owner as the permissions granted, but they can run level 5 commands. 

**Error Logs**
There arent any error logs, it just states that the bot is *removing perms from everyone* and then the permissions remain. 

**Screenshots**
https://i.imgur.com/0xUF1D6.png

**Comment by ChrisvanChip** [comment]
Is your bot not in any other server and is the "public bot" switch toggled off at the Discord developer panel?

However intentional by Modmail's developer, there is a security issue at Modmail that makes anyone able to gain owner, unless you have toggled "public bot" off. Otherwise, abusers can just invite the bot to a server they own & mess up your commands with level 5, as Modmail allows the guild owner to manage the bot (regardless of any permission configurations).

**Comment by StephenDaDev** [comment]
The information provided by @ChrisvanChip is **false**. It was fixed in [this commit](https://github.com/kyb3r/modmail/commit/a26cd4e583ccf2061029a16a09f5cf1f8ff118d3#diff-3ce7c784d4d5f867e79a3e830faee126). I encourage @ChrisvanChip to review the inner-workings of the bot before spreading incorrect and potentially worrying information.

**Comment by ChrisvanChip** [comment]
> The information provided by @ChrisvanChip is **false**. It was fixed in [this commit](https://github.com/kyb3r/modmail/commit/a26cd4e583ccf2061029a16a09f5cf1f8ff118d3#diff-3ce7c784d4d5f867e79a3e830faee126). I encourage @ChrisvanChip to review the inner-workings of the bot before spreading incorrect and potentially worrying information.

Ah, my apologies, thanks for letting me know. I had assisted someone earlier with the same problem, but they were probably using an older version. Thanks for the heads-up :)

**Comment by fourjr** [comment]
I think this is resolved? Let me know if it is otherwise
