### ISSUE TITLE
[Suggestion] Give users the ability to message modmail anonymously

### ISSUE THREAD

**Issue by MiTonder** [kyb3r/modmail#313]
It could be cool to have a feature for people to message modmail anonymously, just like staff and admin can message anonymously.

Ex. Culture problem on the server, user's too embarrased to admit it to the mod team directly, but still wants to report it.

**Suggested by: Melkor#0417**

**Comment by StephenDaDev** [comment]
Maybe still have the ability to reply showing who you are (un-anon?) by making the anon feature require you to send a certain phrase or symbol at the beginning of the thread. Channel Name?

**Comment by kyb3r** [comment]
This can be implemented as a command `!anonmodmail` which starts a new thread where the recipient is anonymous #224

**Comment by AhmedXL** [comment]
That can be easily abused, at lest give them the illusion that its anonymous and leader or bot owner gets dm from the bot saying that this user#0000 activated anonmodmail

**Comment by StephenDaDev** [comment]
Could have an option to see it in the logs, like another switch to show real identity

**Comment by Taaku18** [comment]
Abuse shouldn’t be the problem, we could make `?block` available in the thread to block the user, when blocked, user is revealed and added to the blocked list; block is a moderator command.

Second, no where in logs should display the anything to do with the user. The user should be only stored in the database, since the point of starting anonymous threads is to be anonymous, an average supporter should never have the choice to see the user behind it. Only the more trusted users with moderator perms can reveal who they are using `?block` as they are more trusted.

**Comment by StephenDaDev** [comment]
Agreed.
