### ISSUE TITLE
[BUG]: permission  

### ISSUE THREAD

**Issue by thinktv10** [kyb3r/modmail#3145]
### Bot Version

3.10.3

### How are you hosting Modmail?

Heroku

### Error Logs

N/A

### Screenshots

People with the admin perm is modmail perm level 3
![D4A63BEC-E05A-4AC0-B25F-5C43B22F19C9](https://user-images.githubusercontent.com/76577009/160306598-bd95f8e3-eda7-4b3a-ab73-80886270476d.jpeg)

### Additional Information

Help pls

**Comment by Cordila** [comment]
You have to set it manually, this should be asked in the support server. [discord.gg/etJNHCQ](https://discord.gg/etJNHCQ)

**Comment by Cordila** [comment]
After discussing this with salem in the support server. Making it clear for everyone:
If a role has admin permissions then the user with that role can use Level 4 commands even if that is not what is needed. From my testing, doesnt look like its possible to set that role to be a regular level.

However this seems intentional here. 
https://github.com/kyb3r/modmail/blob/4e54fd45d3e9cc84d3890994eac22a58a8cb4784/core/checks.py#L57
