### ISSUE TITLE
Skip check errors

### ISSUE THREAD

**Issue by Cordila** [kyb3r/modmail#3163]
### Bot Version

dev14

### How are you hosting Modmail?

Other

### Error Logs

https://hastebin.cc/gubamibako

### Screenshots

The jsk exec command to bypass checks fails. seems like an issue with modmail using it here
https://github.com/kyb3r/modmail/blob/77489be6a21cf4befeab1dc7fa2c2d2098104cbc/bot.py#L1102

not sure, didnt have this issue before

**Comment by Jerrie-Aries** [comment]
Yes. `discord.ext.commands.Bot` used to have the `._skip_check` method and it has been removed. This has been fixed in `ModmailBot.get_contexts` method with:
https://github.com/kyb3r/modmail/blob/77489be6a21cf4befeab1dc7fa2c2d2098104cbc/bot.py#L983
but not in the `ModmailBot.get_context` (without `s`).

Maybe create a PR to fix that as well. 😃
