### ISSUE TITLE
[BUG]: silently closing threads not working as intended

### ISSUE THREAD

**Issue by livvie0001** [kyb3r/modmail#3214]
### Bot Version

4.0.1

### How are you hosting Modmail?

Heroku

### Error Logs

https://hastebin.cc/oreyuqifum

### Screenshots

![F1722545-B9E3-486B-A1BC-BAB369465978](https://user-images.githubusercontent.com/80555505/193720329-79a2db45-2b92-4c59-8f27-08d4876266ee.jpeg)

### Additional Information

When using silent close as instructed in the help menu, the thread is closed with the message ‘silently’ rather than closing silently as intended. Placing ‘silently’ before the timeframe works as intended.

**Comment by lidistat67** [comment]
The command does not work like that. You only need to provide the hour. So for example ?close 12h This thread has been closed for inactivity would close the thread in 12 hours and provide the message "This thread has been closed for inactivity"

**Comment by Jerrie-Aries** [comment]
It used to work on older version tho.
![close_silent](https://user-images.githubusercontent.com/70805800/193826489-1482e950-a1ea-4071-8189-9f86c8e9a027.jpg)


And as she said there the help menu says otherwise:
> When using silent close as instructed in the help menu ...

![help_close](https://user-images.githubusercontent.com/70805800/193828616-71c32f40-19f3-43da-9049-2ab36e63aeb9.jpg)


It may need to be updated.
Just flip the `in 10m silently` to `silently in 10m`.

**Comment by lidistat67** [comment]
Thank you both. I've made a pull request :)

**Comment by Taaku18** [comment]
PR #3215 fixes the order in the help example. Maybe in the future, we'll support `in 10m silently` format.
