### ISSUE TITLE
Move to certain category if a keyword is met

### ISSUE THREAD

**Issue by TheFatalKiller** [kyb3r/modmail#649]
I suggest that there should be a command where you can specify a key word and specify what category the thread will move to if the key word is met. For example if someone started a thread saying “I would like to partner”, or “partner?” It would go to the partner category automatically.
edit: I also think it would be a good idea if the key word is met and once it’s moved to the category a certain role would be mentioned (which the user has set up)

**Comment by Taaku18** [comment]
What type of rules should it implement? Should it just be a straight “is the keyword present” check? 

For example: If “partner” is present, will “partnership” and “partners” be matched?

If so:

0. Basic presence match.
 
If not, then we need to introduce word boundaries: here’s three ways we can do that:

1. There must be a word boundary around the keyword. (limits so that “partnership” wouldn’t be matched for “partner”) 

2. Allow a custom escape (“\b”), for which when you encounter “\b” in your keyword, a word break is expected. (“\bpartner\b” will prevent “partnership” to be matched; allows more flexibility)

3. Simply allow the use of Regex. (The maximum flexibility; however, most users wouldn’t know how to use it and become confused)

[![](https://api.gh-polls.com/poll/01DY4E2SPSP6CKXA9NNB9Q9G9K/Option%200)](https://api.gh-polls.com/poll/01DY4E2SPSP6CKXA9NNB9Q9G9K/Option%200/vote)
[![](https://api.gh-polls.com/poll/01DY4E2SPSP6CKXA9NNB9Q9G9K/Option%201)](https://api.gh-polls.com/poll/01DY4E2SPSP6CKXA9NNB9Q9G9K/Option%201/vote)
[![](https://api.gh-polls.com/poll/01DY4E2SPSP6CKXA9NNB9Q9G9K/Option%202)](https://api.gh-polls.com/poll/01DY4E2SPSP6CKXA9NNB9Q9G9K/Option%202/vote)
[![](https://api.gh-polls.com/poll/01DY4E2SPSP6CKXA9NNB9Q9G9K/Option%203)](https://api.gh-polls.com/poll/01DY4E2SPSP6CKXA9NNB9Q9G9K/Option%203/vote)
[![](https://api.gh-polls.com/poll/01DY4E2SPSP6CKXA9NNB9Q9G9K/This%20feature%20isn%E2%80%99t%20needed)](https://api.gh-polls.com/poll/01DY4E2SPSP6CKXA9NNB9Q9G9K/This%20feature%20isn%E2%80%99t%20needed/vote)

- - -

Apart from the previous, should multiple keywords all present, and/or any of the multiple keywords be present, be a feature?

[![](https://api.gh-polls.com/poll/01DY4EHS7ZERQAW6TCDHMYT9SE/All%20keywords)](https://api.gh-polls.com/poll/01DY4EHS7ZERQAW6TCDHMYT9SE/All%20keywords/vote)
[![](https://api.gh-polls.com/poll/01DY4EHS7ZERQAW6TCDHMYT9SE/Any%20keyword)](https://api.gh-polls.com/poll/01DY4EHS7ZERQAW6TCDHMYT9SE/Any%20keyword/vote)
[![](https://api.gh-polls.com/poll/01DY4EHS7ZERQAW6TCDHMYT9SE/Support%20for%20both)](https://api.gh-polls.com/poll/01DY4EHS7ZERQAW6TCDHMYT9SE/Support%20for%20both/vote)
[![](https://api.gh-polls.com/poll/01DY4EHS7ZERQAW6TCDHMYT9SE/Unnecessary%20-%20single%20keyword%20present)](https://api.gh-polls.com/poll/01DY4EHS7ZERQAW6TCDHMYT9SE/Unnecessary%20-%20single%20keyword%20present/vote)

- - -

> Please note: commenting on GitHub Issues are open to everyone in the community, not only limited to the author and contributors. Feel free to discuss your thoughts below and vote!
