### ISSUE TITLE
Allow only users with a specific role to DM Modmail

### ISSUE THREAD

**Issue by shetos126** [kyb3r/modmail#75]
### Suggestion 1
An option where any message in a thread is being relayed to the user

### Suggestion 2
Only users with X roles are allowed to create new threads (DM the bot)

**Comment by kyb3r** [comment]
For the first suggestion, I don't think its a good idea since in my experience mods talk and discuss within the channel about the current thread. If we implement replying without a command, discussion within the channel won't be possible. Can you elaborate further on the second suggestion though?

**Comment by shetos126** [comment]
> 2ns

let the bot receive the messages from users with specific role no't anyone
`Ex`: **User** with youtuber role & **another user** with any role 
the bot received from user with youtuber role only

**Comment by fourjr** [comment]
What are the use cases of this feature?

**Comment by WebKide** [comment]
There wasn't, so here it is the new issue with that idea
#120

**Comment by EthanC** [comment]
@kyb3r +1 for an option to forward any message sent in a thread, rather than requiring the reply command to be used.

I'm currently looking to migrate my current Mod Mail solution to this one, however the lack of this feature is a real downer for my mod team. We discuss Mod Mail in the Moderators channel, anything that's important enough to be archived can be added using the note command.

**Comment by kyb3r** [comment]
Possibly could be implemented as a config option `no_command_reply`

**Comment by kyb3r** [comment]
Added this in v2.17.0
