### ISSUE TITLE
Paginated info embed for threads

### ISSUE THREAD

**Issue by maidos** [kyb3r/modmail#88]
Example would be adding few emoji below the rich embed. Cross can be closing the ticket. Book icon can be assigning the ticket to a specific moderator which auto mention the target user.

I suggest another thing, adding pagination utilizing reaction emoji arrows to change the current rich embed. Example right arrow would take you to page 2 and the current rich embed will change to example Past logs, page 3 can be MISC data about the user who submitted the ticket/thread.

We can condense the current way the rich embed is displaying. We dont need to know the current nickname because the bot has mentioned the user already so you can click on the name. 
Member number is not a vital information that people should need, instead that info can be moved to page 3 of rich embed

![](https://i.imgur.com/q4p0Bse.png)

**Comment by fourjr** [comment]
1. Assigning certain mods to certain different modmail threads is a unique feature suggestion and should have its own dedicated issue.
2. Paginated info embeds are a bad idea in our opinion. Anyone else would be able to play with reactions or accidentally close the thread.
3. Since the message has to be "listening" as long as the thread is active (normal messages have a timeout before they stop "listening" and editing), it might eat up more resources than necessary and tbh doesn't seem worth it.
Thanks for the issue though :P

If you have a counter-point, you can comment in in this issue.

**Comment by fourjr** [comment]
We have removed member number from info embed as per your suggestions in v2 (#82)

Nickname is there in case user changes midway in a conversation.

**Comment by maidos** [comment]
2. i disagree on that. If you are afraid that misclick happends then simply add a confirmation reaction ontop of it.  or have a delayed event after you click emoji. if you react on an emoji after 5 seconds the ticket close. if you react and unreact less than 5 seconds, the ticket wont autoclose. this prevent the missclick alltogether.

Regarding resource intensive inquire, it isnt.
Most libraries limit it to the ~10k most recent messages
Unless you use the raw event

**Comment by fourjr** [comment]
I'll reopen this for now and set as low priority.

If you want, feel free to submit a PR. Use the raw events

**Comment by StephenDaDev** [comment]
The issue with the 5 seconds, is there is a good chance someone will click on an emoji and not even notice they did it, and then poof there goes the thread. but the assign to moderator, or claim thread idea is wonderful

**Comment by Taaku18** [comment]
This ties in with #300. Feature discussions will be moved over there.
